import { useState } from 'react';
import { Repl, type Files } from 'mini-react-repl';
import { MonacoReplEditor } from 'mini-react-repl/editor-monaco';
import 'mini-react-repl/theme.css';

// optional: self-host swc-wasm (see README for details)
import swcWasmUrl from '@swc/wasm-web/wasm_bg.wasm?url';

import initialAppSource from './initial/App.tsx?raw';

// Both generated by `pnpm build:vendor` (gitignored). `prodVendor` is the same
// manifest built with `--prod`: production React, about half the size, but no
// Fast Refresh and no element picker. `?prod` renders the demo against it.
import { customVendor } from './vendor.generated';
import { prodVendor } from './vendor.prod.generated';

const HELLO: Files = {
  'App.tsx': initialAppSource,
};

const PROD = typeof window !== 'undefined' ? new URLSearchParams(window.location.search).has('prod') : false;

export function App() {
  const [files, setFiles] = useState<Files>(HELLO);

  return (
    <Repl
      files={files}
      onFilesChange={setFiles}
      vendor={PROD ? prodVendor : customVendor}
      editor={MonacoReplEditor}
      swcWasmUrl={swcWasmUrl}
    />
  );
}
