import { useState } from 'react';
import { Repl, type Files } from 'mini-react-repl';
import { MonacoReplEditor } from 'mini-react-repl/editor-monaco';
import 'mini-react-repl/theme.css';

// optional: self-host swc-wasm (see README for details)
import swcWasmUrl from '@swc/wasm-web/wasm_bg.wasm?url';

import initialAppSource from './initial/App.tsx?raw';

// Generated by `pnpm build:vendor` (gitignored)
import { customVendor } from './vendor.generated';

const HELLO: Files = {
  'App.tsx': initialAppSource,
};

export function App() {
  const [files, setFiles] = useState<Files>(HELLO);

  return (
    <Repl
      files={files}
      onFilesChange={setFiles}
      vendor={customVendor}
      editor={MonacoReplEditor}
      swcWasmUrl={swcWasmUrl}
    />
  );
}
