#!/usr/bin/env node
/**
 * Bundles `src/runtime/runtime.ts` (the iframe-side code) into a single
 * ESM string and emits it as a TypeScript module so the rest of the
 * library can embed it in the srcdoc preview HTML.
 *
 * React, ReactDOM, and react-refresh stay external — those resolve through
 * the iframe's import map at runtime.
 */

import { build } from 'esbuild';
import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

async function bundle(entry) {
  const result = await build({
    entryPoints: [resolve(root, entry)],
    bundle: true,
    format: 'esm',
    target: 'es2022',
    platform: 'browser',
    write: false,
    minify: false,
    sourcemap: 'inline',
    external: ['react', 'react-dom', 'react-dom/client', 'react-refresh/runtime'],
    logLevel: 'warning',
  });
  const code = result.outputFiles[0]?.text;
  if (!code) throw new Error(`bundle produced no output: ${entry}`);
  return code;
}

const preambleCode = await bundle('src/runtime/preamble.ts');
const runtimeCode = await bundle('src/runtime/runtime.ts');

const out = `// AUTO-GENERATED by scripts/build-runtime.mjs — do not edit.
/* eslint-disable */
export const PREAMBLE_CODE: string = ${JSON.stringify(preambleCode)}
export const RUNTIME_CODE: string = ${JSON.stringify(runtimeCode)}
`;

const outPath = resolve(root, 'src/runtime/runtime.bundled.ts');
await mkdir(dirname(outPath), { recursive: true });
await writeFile(outPath, out, 'utf8');

console.log(
  `✓ runtime bundle written to ${outPath} (preamble ${(preambleCode.length / 1024).toFixed(1)} kB, runtime ${(runtimeCode.length / 1024).toFixed(1)} kB)`,
);
