#!/usr/bin/env node
/**
 * Bundles `src/inspect/picker/picker.ts` (the iframe-side inspect picker)
 * into a single self-contained ESM string and emits it as a TypeScript
 * module. `<InspectMode/>` posts this source to the iframe runtime, which
 * builds a `blob:` URL and `import()`s it on first activation — so the
 * picker rides the same cross-origin postMessage + blob-URL channel that
 * user modules already use, no `iframe.contentDocument` injection required.
 *
 * `@jridgewell/trace-mapping` is bundled in. Nothing the picker imports is
 * external — the whole bundle has to run in a fresh iframe with only the
 * iframe import map and `window.__repl__` available.
 */

import { build } from 'esbuild';
import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const result = await build({
  entryPoints: [resolve(root, 'src/inspect/picker/picker.ts')],
  bundle: true,
  // ESM so the iframe runtime can `import(blobUrl)` the bundle. Top-level
  // statements (the picker's `window.addEventListener('message', ...)`
  // registrations) run on first import, exactly once per iframe lifetime.
  format: 'esm',
  target: 'es2022',
  platform: 'browser',
  write: false,
  minify: true,
  sourcemap: false,
  // No externals: trace-mapping (and everything else the picker imports)
  // must be inlined so the bundle works inside the iframe with no network.
  logLevel: 'warning',
});

const code = result.outputFiles[0]?.text;
if (!code) throw new Error('picker bundle produced no output');

const out = `// AUTO-GENERATED by scripts/build-picker.mjs — do not edit.
/* eslint-disable */
export const INSPECT_PICKER_CODE: string = ${JSON.stringify(code)};
`;

const outPath = resolve(root, 'src/inspect/picker.bundled.ts');
await mkdir(dirname(outPath), { recursive: true });
await writeFile(outPath, out, 'utf8');

console.log(
  `✓ picker bundle written to ${outPath} (${(code.length / 1024).toFixed(1)} kB minified)`,
);
