#!/usr/bin/env node
/**
 * Bundles `src/inspect/picker/picker.ts` (the iframe-side inspect picker)
 * into a single self-contained ESM string and emits it as a TypeScript
 * module so `preview-html.ts` can inline it as a third `<script type="module">`.
 *
 * `@jridgewell/trace-mapping` is bundled in. Nothing the picker imports is
 * external — the whole bundle has to run in a fresh iframe with only the
 * iframe import map and `window.__repl__` available.
 */

import { build } from 'esbuild';
import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const result = await build({
  entryPoints: [resolve(root, 'src/inspect/picker/picker.ts')],
  bundle: true,
  // IIFE so the bundle runs as a classic `<script>` (no `type="module"`).
  // Classic scripts with inline content execute synchronously on append,
  // which lets `<InspectMode>` lazy-inject the picker and immediately post
  // `inspect:enable` without any ready-handshake roundtrip.
  format: 'iife',
  target: 'es2022',
  platform: 'browser',
  write: false,
  minify: true,
  sourcemap: false,
  // No externals: trace-mapping (and everything else the picker imports)
  // must be inlined so the bundle works inside the iframe with no network.
  logLevel: 'warning',
});

const code = result.outputFiles[0]?.text;
if (!code) throw new Error('picker bundle produced no output');

const out = `// AUTO-GENERATED by scripts/build-picker.mjs — do not edit.
/* eslint-disable */
export const INSPECT_PICKER_CODE: string = ${JSON.stringify(code)};
`;

const outPath = resolve(root, 'src/inspect/picker.bundled.ts');
await mkdir(dirname(outPath), { recursive: true });
await writeFile(outPath, out, 'utf8');

console.log(
  `✓ picker bundle written to ${outPath} (${(code.length / 1024).toFixed(1)} kB minified)`,
);
